import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'

type Incident = { incident_id: string; title: string; status: string; severity: string; event_count: number }
type Client = { client_id: string; name: string; environment: string; service: string; status: string; incidents: number; last_seen?: string }
type Trace = { agent: string; status?: string; output: string }
type Action = { action: string; risk: string; reason?: string; guardrail?: string }
type Analysis = { root_cause: string; confidence: number; summary: string; hypothesis: string; evidence: string[]; rag_context: Array<{ id: string; title: string; content: string; score: number }>; steps: Array<{ stage: string; finding: string; evidence?: string[] }>; diagnosis_steps?: Array<{ stage: string; finding: string; evidence?: string[] }>; actions: Action[]; repair_steps?: Array<{ stage: string; finding: string; validation?: string }>; agent_trace: Trace[]; llm_used: boolean; evaluation?: Record<string, number | string>; approval_state?: string }
type Metrics = Record<string, any>

type View = 'Overview' | 'Clients' | 'Incidents' | 'Investigation' | 'Agents' | 'Evidence' | 'Approvals' | 'Metrics' | 'Audit' | 'Architecture'
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000'
const DEMO_EMAIL = import.meta.env.VITE_DEMO_EMAIL || 'engineer@tracegaurd.ai'
const DEMO_PASSWORD = import.meta.env.VITE_DEMO_PASSWORD || 'TraceGaurd@123'

async function api<T = any>(path: string, options: RequestInit = {}, token?: string): Promise<T> {
  const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } })
  let data: any = {}
  try { data = await response.json() } catch { /* empty */ }
  if (!response.ok) throw new Error(data.detail || 'Request failed')
  return data as T
}

const Metric = ({ label, value, sub }: { label: string; value: React.ReactNode; sub: string }) => <div className="metric"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>
const CardHead = ({ title, meta }: { title: string; meta: string }) => <div className="card-head"><h3>{title}</h3><span>{meta}</span></div>
const Empty = ({ text }: { text: string }) => <div className="empty">◌<p>{text}</p></div>

function Login({ onLogin }: { onLogin: (email: string, password: string) => Promise<void> }) {
  const [email, setEmail] = useState(DEMO_EMAIL), [password, setPassword] = useState(DEMO_PASSWORD), [error, setError] = useState('')
  return <div className="login"><div className="login-visual"><div className="orb orb1"/><div className="orb orb2"/><div className="login-grid"/><div className="hero-copy"><div className="logo">TRACE<span>GAURD</span></div><p className="kicker">AUTONOMOUS INCIDENT INTELLIGENCE</p><h1>Resolve incidents<br/><i>with evidence.</i></h1><p>Multi-agent diagnosis, RAG-grounded reasoning and human-gated remediation for production systems.</p><div className="mini-flow"><b>TELEMETRY</b><span>→</span><b>LANGGRAPH</b><span>→</span><b>RCA</b><span>→</span><b>GUARDRAIL</b></div></div></div><div className="login-form"><div><div className="logo dark">TRACE<span>GAURD</span></div><p className="kicker">ENGINEER CONSOLE</p><h2>Welcome back</h2><p className="muted">Sign in to your incident command center.</p></div><form onSubmit={async e => { e.preventDefault(); setError(''); try { await onLogin(email, password) } catch (x) { setError((x as Error).message) } }}><label>Work email<input value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <div className="error">{error}</div>}<button className="primary wide">Enter Command Center <span>↗</span></button></form><div className="demo">Demo access · {DEMO_EMAIL} · {DEMO_PASSWORD}</div></div></div>
}

function App() {
  const [token, setToken] = useState(localStorage.getItem('tg_token')), [email, setEmail] = useState(localStorage.getItem('tg_email') || DEMO_EMAIL)
  const [view, setView] = useState<View>('Overview'), [incidents, setIncidents] = useState<Incident[]>([]), [clients, setClients] = useState<Client[]>([]), [metrics, setMetrics] = useState<Metrics>({}), [selected, setSelected] = useState<string | null>(null), [analysis, setAnalysis] = useState<Analysis | null>(null), [audit, setAudit] = useState<any[]>([]), [busy, setBusy] = useState(false), [err, setErr] = useState('')
  const load = async () => { if (!token) return; try { const [i, c, m, a] = await Promise.all([api<Incident[]>('/api/v1/incidents', {}, token), api<Client[]>('/api/v1/clients', {}, token), api<Metrics>('/api/v1/metrics', {}, token), api<any[]>('/api/v1/audit', {}, token)]); setIncidents(i); setClients(c); setMetrics(m); setAudit(a); setErr('') } catch (e) { setErr((e as Error).message) } }
  useEffect(() => { load() }, [token])
  const login = async (e: string, p: string) => { const r = await api<any>('/api/v1/auth/login', { method: 'POST', body: JSON.stringify({ email: e, password: p }) }); localStorage.setItem('tg_token', r.access_token); localStorage.setItem('tg_email', r.engineer || e); setToken(r.access_token); setEmail(r.engineer || e) }
  const logout = () => { localStorage.clear(); setToken(null); setAnalysis(null) }
  const analyze = async (id: string) => { setSelected(id); setBusy(true); try { setAnalysis(await api<Analysis>(`/api/v1/incidents/${id}/analysis`, {}, token!)); setView('Investigation') } catch (e) { setErr((e as Error).message) } finally { setBusy(false) } }
  const simulate = async () => { setBusy(true); try { await api('/api/v1/simulate/checkout', { method: 'POST' }, token!); await load() } catch (e) { setErr((e as Error).message) } finally { setBusy(false) } }
  const approve = async (action: string, yes: boolean) => { if (!selected) return; setBusy(true); try { const r = await api<any>(`/api/v1/incidents/${selected}/approve`, { method: 'POST', body: JSON.stringify({ action, approved: yes }) }, token!); if (yes && r.approval_id) await api(`/api/v1/incidents/${selected}/execute`, { method: 'POST', body: JSON.stringify({ action, approval_id: r.approval_id }) }, token!); await load(); await analyze(selected) } catch (e) { setErr((e as Error).message) } finally { setBusy(false) } }
  if (!token) return <Login onLogin={login} />
  const nav: Array<[View, string]> = [['Overview', '◈'], ['Clients', '◎'], ['Incidents', '⌁'], ['Investigation', '✦'], ['Agents', '◌'], ['Evidence', '⌕'], ['Approvals', '✓'], ['Metrics', '▥'], ['Audit', '≡'], ['Architecture', '◇']]
  return <div className="shell"><aside><div className="brand">TRACE<span>GAURD</span></div><div className="side-label">INCIDENT COMMAND</div><nav>{nav.map(([n, i]) => <button className={view === n ? 'nav active' : 'nav'} onClick={() => setView(n)} key={n}><span className="ico">{i}</span>{n}{n === 'Incidents' && incidents.length > 0 && <b className="count">{incidents.length}</b>}</button>)}</nav><div className="side-bottom"><div className="status"><span/> ALL SYSTEMS OPERATIONAL</div><div className="engineer"><div className="avatar">{email[0].toUpperCase()}</div><div><b>{email.split('@')[0]}</b><small>Software Engineer</small></div></div><button className="logout" onClick={logout}>↪ Sign out</button></div></aside><main><header className="top"><div><p className="crumb">TRACEGAURD / {view.toUpperCase()}</p><h1>{view === 'Overview' ? 'Command Center' : view}</h1><p className="muted">Evidence-first incident response with human-controlled remediation.</p></div><div className="top-actions"><span className="live"><i/> LIVE MONITORING</span><button className="primary" onClick={simulate} disabled={busy}>＋ Simulate Incident</button></div></header>{err && <div className="error banner">{err}</div>}{view === 'Overview' && <Overview metrics={metrics} incidents={incidents} clients={clients} onIncident={analyze} onSimulate={simulate} />} {view === 'Clients' && <Clients clients={clients} />} {view === 'Incidents' && <Incidents incidents={incidents} selected={selected} onSelect={analyze} />} {view === 'Investigation' && <Investigation analysis={analysis} selected={selected} busy={busy} onApprove={approve} onEvidence={() => setView('Evidence')} onAgents={() => setView('Agents')} />} {view === 'Agents' && <Agents trace={analysis?.agent_trace || []} />} {view === 'Evidence' && <Evidence data={analysis?.rag_context || []} evidence={analysis?.evidence || []} />} {view === 'Approvals' && <Approvals analysis={analysis} busy={busy} onApprove={approve} />} {view === 'Metrics' && <Metrics metrics={metrics} analysis={analysis} />} {view === 'Audit' && <Audit audit={audit} />} {view === 'Architecture' && <Architecture />}</main></div>
}

function Overview({ metrics, incidents, clients, onIncident, onSimulate }: { metrics: Metrics; incidents: Incident[]; clients: Client[]; onIncident: (id: string) => void; onSimulate: () => void }) { return <div className="page"><div className="hero-card"><div><span className="pill">AI INCIDENT COMMANDER · v3.4</span><h2>From signal to<br/><em>verified resolution.</em></h2><p>TraceGaurd correlates telemetry, retrieves operational evidence and produces an explainable root-cause hypothesis before any remediation is allowed.</p><div className="hero-buttons"><button className="primary" onClick={onSimulate}>Run live simulation ↗</button><button className="ghost">Architecture mapped ↓</button></div></div><div className="architecture"><div className="arch-center">AI<br/><small>CORE</small></div>{['INGEST', 'CORRELATE', 'RAG', 'RCA', 'GUARDRAIL', 'VERIFY'].map((x, i) => <div className={`arch-node n${i}`} key={x}><span>{String(i + 1).padStart(2, '0')}</span>{x}</div>)}</div></div><div className="metrics-grid"><Metric label="Active incidents" value={metrics.active_incidents ?? incidents.length} sub="Across monitored clients"/><Metric label="Clients monitored" value={metrics.clients_monitored ?? clients.length} sub="Live service inventory"/><Metric label="Remediations" value={metrics.actions_executed ?? 0} sub="Human-approved executions"/><Metric label="Audit events" value={metrics.audit_events ?? 0} sub="Fully traceable"/></div><div className="two"><div className="card"><CardHead title="Incident queue" meta={`${incidents.length} detected`}/>{incidents.slice(0, 6).map(x => <button className="incident-row" onClick={() => onIncident(x.incident_id)} key={x.incident_id}><div><span className="incident-id">{x.incident_id}</span><b>{x.title}</b></div><span className="sev">{x.severity}</span><span>{x.event_count} events</span><span>Investigate →</span></button>)}{!incidents.length && <Empty text="No active incidents. Launch the simulation to demonstrate the full workflow."/>}</div><div className="card"><CardHead title="Client health" meta="REAL TIME"/>{clients.slice(0, 6).map(c => <div className="health-row" key={c.client_id}><span className="health-dot"/><div><b>{c.name}</b><small>{c.service} · {c.environment}</small></div><span className="health-ok">{c.status || 'ONLINE'}</span></div>)}</div></div></div> }

function Clients({ clients }: { clients: Client[] }) { return <div className="page"><div className="section-intro"><span className="pill">MONITORING PLANE</span><h2>Client service inventory</h2><p>Each client has an isolated identity and can stream signed telemetry into the ingestion layer.</p></div><div className="client-grid">{clients.map(c => <div className="client-card" key={c.client_id}><div className="client-top"><div className="service-icon">⌁</div><span className="online-badge"><i/> {c.status || 'ONLINE'}</span></div><h3>{c.name}</h3><p>{c.service}</p><div className="client-meta"><span>{c.environment}</span><b>{c.incidents} incidents</b></div><div className="bar"><i style={{ width: `${Math.min(100, 20 + c.incidents * 12)}%` }}/></div><small>ID · {c.client_id}</small></div>)}</div></div> }

function Incidents({ incidents, selected, onSelect }: { incidents: Incident[]; selected: string | null; onSelect: (id: string) => void }) { return <div className="page"><div className="section-intro"><span className="pill">DETECTION & CORRELATION</span><h2>Incident queue</h2><p>Prioritized signals waiting for multi-agent investigation.</p></div><div className="card table"><div className="thead"><span>INCIDENT</span><span>SEVERITY</span><span>EVENTS</span><span>STATUS</span></div>{incidents.map(x => <button className={`trow ${selected === x.incident_id ? 'row-active' : ''}`} onClick={() => onSelect(x.incident_id)} key={x.incident_id}><b>{x.incident_id}</b><span className="sev">{x.severity}</span><span>{x.event_count}</span><span className="status-chip">OPEN · Investigate →</span></button>)}{!incidents.length && <Empty text="Incident queue is clear."/>}</div></div> }

function Investigation({ analysis, selected, busy, onApprove, onEvidence, onAgents }: { analysis: Analysis | null; selected: string | null; busy: boolean; onApprove: (action: string, yes: boolean) => void; onEvidence: () => void; onAgents: () => void }) { if (!analysis) return <div className="page"><Empty text="Select an incident from the queue to begin investigation."/></div>; const steps = analysis.diagnosis_steps || analysis.steps || []; return <div className="page"><div className="invest-head"><div><span className="pill">INCIDENT · {selected}</span><h2>Root-cause investigation</h2><p>LangGraph orchestration · {analysis.llm_used ? 'LLM reasoning enabled' : 'deterministic safety fallback'} · RAG grounded</p></div><div className="confidence"><small>HYPOTHESIS CONFIDENCE</small><strong>{analysis.confidence}%</strong><div className="ring" style={{ '--p': `${analysis.confidence}%` } as React.CSSProperties}/></div></div><div className="cause-card"><div className="cause-title"><span>01</span><div><small>LEADING HYPOTHESIS</small><h3>{analysis.root_cause}</h3></div></div><p>{analysis.summary}</p><div className="cause-foot"><span>Evidence supported · Not a guarantee</span><span>{analysis.evidence?.length || 0} evidence signals</span></div></div><Workflow/><div className="two"><div className="card"><CardHead title="Diagnosis steps" meta={`${steps.length} GENERATED`}/>{steps.map((s, i) => <div className="step" key={i}><b>{String(i + 1).padStart(2, '0')}</b><div><strong>{s.stage}</strong><p>{s.finding}</p><small>{(s.evidence || []).join(' · ') || 'Derived from correlated telemetry'}</small></div></div>)}</div><div className="card"><CardHead title="Repair plan" meta="HUMAN GATED"/>{(analysis.repair_steps || []).map((s, i) => <div className="repair" key={i}><span>✓</span><div><strong>{s.stage}</strong><p>{s.finding}</p></div></div>)}</div></div><div className="card approval-card"><CardHead title="Guardrail decision" meta={analysis.approval_state || 'PENDING REVIEW'}/>{analysis.actions.map((a, i) => <div className="action-row" key={i}><div><strong>{a.action}</strong><p>{a.reason}</p></div><span className={`risk ${String(a.risk).toLowerCase()}`}>{a.risk}</span>{a.risk === 'APPROVAL' && <div><button disabled={busy} className="primary small" onClick={() => onApprove(a.action, true)}>Approve & execute</button><button disabled={busy} className="ghost small" onClick={() => onApprove(a.action, false)}>Reject</button></div>}</div>)}</div><div className="quick-links"><button onClick={onEvidence}>⌕ Inspect RAG evidence</button><button onClick={onAgents}>◌ Open agent trace</button></div></div> }

function Workflow() { return <div className="workflow">{['Ingestion', 'Noise filter', 'Correlation', 'RAG retrieval', 'Root cause', 'Diagnostics', 'Guardrail', 'Timeline'].map((x, i) => <div key={x}><span>{String(i + 1).padStart(2, '0')}</span><b>{x}</b>{i < 7 && <i>→</i>}</div>)}</div> }
function Agents({ trace }: { trace: Trace[] }) { return <div className="page"><div className="section-intro"><span className="pill">LANGGRAPH OBSERVABILITY</span><h2>Agent execution trace</h2><p>Every reasoning stage is visible, ordered and auditable.</p></div><div className="agent-list">{trace.map((a, i) => <div className="agent-card" key={i}><div className="agent-num">{String(i + 1).padStart(2, '0')}</div><div><div className="agent-name"><h3>{a.agent}</h3><span>✓ {a.status || 'COMPLETED'}</span></div><p>{a.output}</p></div><time>COMPLETE</time></div>)}{!trace.length && <Empty text="Run an incident investigation to populate the agent trace."/>}</div></div> }
function Evidence({ data, evidence }: { data: Analysis['rag_context']; evidence: string[] }) { return <div className="page"><div className="section-intro"><span className="pill">RAG · GROUNDED REASONING</span><h2>Evidence vault</h2><p>Retrieved runbooks and incident evidence used to support the diagnosis.</p></div><div className="evidence-grid">{data.map((d, i) => <div className="evidence-card" key={i}><div className="e-head"><span>RUNBOOK</span><b>{Math.round((d.score || 0) * 100)}%</b></div><h3>{d.title || d.id}</h3><p>{d.content}</p><small>Retrieved by RAG Agent · {d.id}</small></div>)}{evidence.map((e, i) => <div className="evidence-card event-card" key={`e${i}`}><div className="e-head"><span>OBSERVED EVIDENCE</span><b>EVENT</b></div><h3>Incident signal</h3><p>{e}</p><small>Observed telemetry · not generated knowledge</small></div>)}</div></div> }
function Approvals({ analysis, busy, onApprove }: { analysis: Analysis | null; busy: boolean; onApprove: (action: string, yes: boolean) => void }) { const pending = analysis?.actions?.filter(a => a.risk === 'APPROVAL') || []; return <div className="page"><div className="section-intro"><span className="pill">HUMAN-IN-THE-LOOP</span><h2>Guardrail & approval center</h2><p>No production mutation is executed from model output alone. The engineer must explicitly approve an allow-listed action.</p></div><div className="approval-banner"><div><span>SAFETY GATE</span><h3>{pending.length ? `${pending.length} action(s) awaiting review` : 'No pending production actions'}</h3><p>Review the root-cause hypothesis, evidence and action risk before approval.</p></div><div className="shield">✓</div></div>{pending.map((a, i) => <div className="card" key={i}><div className="action-row"><div><strong>{a.action}</strong><p>{a.reason}</p></div><span className="risk approval">APPROVAL</span><div><button disabled={busy} className="primary small" onClick={() => onApprove(a.action, true)}>Approve</button><button disabled={busy} className="ghost small" onClick={() => onApprove(a.action, false)}>Reject</button></div></div></div>)}</div> }
function Metrics({ metrics, analysis }: { metrics: Metrics; analysis: Analysis | null }) { const evaluation = analysis?.evaluation || {}; return <div className="page"><div className="section-intro"><span className="pill">EVALUATION & OBSERVABILITY</span><h2>System evaluation</h2><p>Operational metrics and evidence-weighted diagnosis quality, surfaced for transparent hackathon judging.</p></div><div className="metric-big-grid"><BigMetric label="Root-cause confidence" value={`${evaluation.root_cause_confidence ?? '—'}%`} /><BigMetric label="Evidence coverage" value={`${evaluation.evidence_coverage ?? '—'}%`} /><BigMetric label="Workflow completeness" value={`${evaluation.workflow_completeness ?? '—'}%`} /><BigMetric label="Diagnosis quality" value={`${evaluation.diagnosis_quality ?? '—'}%`} /></div><div className="card"><CardHead title="Operational metrics" meta="LIVE"/><div className="ops"><div><span>Active incidents</span><b>{metrics.active_incidents ?? 0}</b></div><div><span>Clients monitored</span><b>{metrics.clients_monitored ?? 0}</b></div><div><span>Approvals</span><b>{metrics.human_approvals ?? 0}</b></div><div><span>Executions</span><b>{metrics.actions_executed ?? 0}</b></div></div><p className="note">Confidence is a hypothesis score derived from evidence and workflow signals; it is not a guarantee of correctness.</p></div></div> }
function BigMetric({ label, value }: { label: string; value: string }) { return <div className="big-metric"><span>{label}</span><strong>{value}</strong><div className="meter"><i style={{ width: value.includes('%') ? value : '0%' }}/></div><small>Evidence-weighted evaluation signal</small></div> }
function Audit({ audit }: { audit: any[] }) { return <div className="page"><div className="section-intro"><span className="pill">IMMUTABLE-STYLE AUDIT VIEW</span><h2>Audit timeline</h2><p>Chronological record of engineer, client and remediation activity.</p></div><div className="card">{audit.map((a, i) => <div className="audit-row" key={i}><span className="audit-dot"/><time>{a.timestamp}</time><b>{a.event}</b><p>{a.actor} · {JSON.stringify(a.details)}</p></div>)}{!audit.length && <Empty text="No audit events yet."/>}</div></div> }

function Architecture() { const groups = [{ title: 'Incident Data Sources', items: ['Logs', 'Alerts', 'Deployments', 'Tickets / Chat'] }, { title: 'Ingestion & Normalization', items: ['Validate', 'Authenticate', 'Normalize'] }, { title: 'Multi-Agent AI Engine · LangGraph + LLM + RAG', items: ['Ingestion Agent', 'Noise Filter Agent', 'Correlation Agent', 'RAG Agent', 'Root Cause Agent', 'Diagnostic Agent', 'Guardrail Agent', 'Timeline Agent'] }, { title: 'RAG Layer', items: ['Runbooks', 'Historical Incidents', 'Vector Retrieval'] }, { title: 'Persistence', items: ['PostgreSQL', 'Incident Events', 'Audit Logs'] }, { title: 'LLM Layer', items: ['OpenAI', 'Deterministic Safety Fallback'] }, { title: 'Human-in-the-Loop', items: ['Review Evidence', 'Approve / Reject', 'Controlled Execution'] }, { title: 'Web Dashboard · React + TypeScript', items: ['Overview', 'AI Analysis', 'Safe Diagnostics', 'Evidence', 'Agent Trace', 'Approvals', 'Metrics', 'Audit'] }, { title: 'Deployment & Infrastructure', items: ['Vercel / Render', 'PostgreSQL', 'Docker', 'GitHub Actions'] }]; return <div className="page"><div className="section-intro"><span className="pill">REFERENCE ARCHITECTURE</span><h2>TraceGaurd system architecture</h2><p>Every box in the reference architecture is represented in the application workflow, with telemetry flowing through LangGraph agents and RAG before human-gated remediation.</p></div><div className="architecture-map">{groups.map((g, i) => <section className={`arch-section arch-${i}`} key={g.title}><div className="arch-title">{g.title}</div><div className="arch-items">{g.items.map(x => <div className="arch-item" key={x}><span>●</span>{x}</div>)}</div>{i < groups.length - 1 && <div className="arch-arrow">↓</div>}</section>)}</div></div> }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
